export const events = [
    
    { id: "1", 
      title: 'event 1', 
      date: '2021-04-01', 
      time: '10 pm',
      class: 'class A',
      material: 'Book',
      join: 'https://www.google.com/',
      details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s," },
    
    { id: "2", 
      title: 'event 2', 
      date: '2021-04-02', 
      time: '10 pm',
      class: 'class A',
      material: 'Book',
      join: 'https://www.google.com/',
      details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"  },
    
    { id: "3", 
      title: 'event 3', 
      date: '2021-04-03', 
      time: '10 pm',
      class: 'class A',
      material: 'Book',
      join: 'https://www.google.com/',
      details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s," },
    
    { id: "4", 
      title: 'event 4', 
      date: '2021-04-04', 
      time: '10 pm',
      class: 'class A',
      material: 'Book',
      join: 'https://www.google.com/',
      details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"  },
    
    { id: "5", 
      title: 'exam 5', 
      date: '2021-04-01',
      time: '10 pm',
      class: 'class A',
      material: 'Book',
      join: 'https://www.google.com/',
      details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s," },
    
    { id: "6", 
      title: 'event 6', 
      date: '2021-04-05',
      time: '10 pm',
      class: 'class A',
      material: 'Book',
      join: 'https://www.google.com/',
      details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"  }
];